#!/bin/bash

start()
{
    /opt/apps/com.sinoparasoft.screenSaver/screenSaver > /dev/null 2>&1 &
}

stop()
{
    killall screenSaver > /dev/null 2>&1
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
