#!/bin/sh
set +e
 
case "$1" in
  configure)

    chmod -R 777 /opt/apps/com.sinoparasoft.mediumissue/files

    # 先停止运行中的进程
    systemctl enable spsbmmediumissue.service
    systemctl daemon-reload
    systemctl restart spsbmmediumissue.service
    ;;
 
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
 
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0