#!/bin/sh
set +e

case "$1" in
  configure)
    chmod -R 755 /opt/apps/com.sinoparasoft.screenSaver/files

    # 重新加载配置并启用、启动服务
    if command -v systemctl >/dev/null 2>&1; then
      systemctl daemon-reload
      systemctl enable spsbmscreensaver.service
      systemctl restart spsbmscreensaver.service
    fi
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0